targets:
  $default:
    builders:
      # gql_build|schema_builder:
      #   enabled: true
      # gql_build|ast_builder:
      #   enabled: true
      # gql_build|data_builder:
      #   enabled: true
      #   options:
      #     schema: cero2|lib/schema.graphql
      # gql_build|var_builder:
      #   enabled: true
      #   options:
      #     schema: cero2|lib/schema.graphql
      # gql_build|serializer_builder:
      #   enabled: true
      #   options:
      #     schema: cero2|lib/schema.graphql

      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: cero2|lib/schema.graphql

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: cero2|lib/schema.graphql
