/*
 * Auto generated by Dart Code Gen 
 */

class SystemConfig {
  static const String apiEndpoint = "http://149.28.16.254:8080"; //dev

  static const String basicAuthKey = "";
  static const String appVersion = "1.0.1";
}
